/** Pictogram names the board can draw. Pure list: shared by the renderer, sanitizer and prompt. */
export const ICON_IDS = [
  "clock",
  "calendar",
  "person",
  "people",
  "book",
  "speech",
  "tv",
  "cook",
  "sleep",
  "work",
  "play",
  "warning",
  "idea",
  "compare",
  "now",
  "habit",
  "football",
  "coffee",
  "write",
  "ear",
  "sun",
  "repeat",
  "leaf",
  "drop",
  "cloud",
  "rain",
  "bolt",
  "atom",
  "flask",
  "magnet",
  "globe",
  "mountain",
  "tree",
  "planet",
  "heart",
  "cell",
  "gear",
  "computer",
  "code",
  "scales",
  "scroll",
  "crown",
  "coin",
  "brain",
  "thermometer",
  "rocket",
  "fire",
  "wind",
  "flag",
  "castle",
] as const;

export type PictogramId = (typeof ICON_IDS)[number];

export function isPictogramId(value: string | undefined): value is PictogramId {
  return !!value && (ICON_IDS as readonly string[]).includes(value);
}
